---
title: "Conclusiones"
output: html_notebook
---


```{r}
install.packages("ggplot2")
```

```{r}
library(ggplot2)

# Cargar los datos
data <- read.csv("full_results.csv", sep = ",")
```

```{r}
# Crear el gráfico de dispersión
ggplot(data, aes(x = n, y = expected_length, color = pivot)) +
  geom_point() +
  labs(title = "Comparación de Pivotes por Longitud Esperada y Tamaño de Muestra",
       x = "Tamaño de Muestra (n)",
       y = "Longitud Esperada",
       color = "Pivote") +
  theme_minimal()
```

```{r}
# Boxplot para la Cobertura por Pivot
ggplot(data, aes(x = pivot, y = coverage, fill = pivot)) +
  geom_boxplot() +
  labs(title = "Cobertura por Pivot",
       x = "Pivote",
       y = "Cobertura") +
  theme_minimal()
```

```{r}
# Boxplot para la Longitud Esperada por Pivot
ggplot(data, aes(x = pivot, y = expected_length, fill = pivot)) +
  geom_boxplot() +
  labs(title = "Longitud Esperada por Pivot",
       x = "Pivote",
       y = "Longitud Esperada") +
  theme_minimal()
```

```{r}
# Histograma para la Longitud Esperada por Pivot
ggplot(data, aes(x = expected_length, fill = pivot)) +
  geom_histogram(binwidth = 0.1, position = "identity", alpha = 0.7) +
  labs(title = "Histograma para la Longitud Esperada por Pivot",
       x = "Longitud Esperada",
       y = "Frecuencia",
       fill = "Pivote") +
  theme_minimal()
```
```{r}
# Filtrar los datos solo para el pivote 1
data_pivot_1 <- subset(data, pivot == "pivot_1")

# Crear el gráfico de dispersión para el pivote 1
ggplot(data_pivot_1, aes(x = n, y = expected_length)) +
  geom_point() +
  labs(title = "Comparación del Pivote 1 por Longitud Esperada y Tamaño de Muestra",
       x = "Tamaño de Muestra (n)",
       y = "Longitud Esperada") +
  theme_minimal()
```
```{r}
# Filtrar los datos solo para el pivote 2
data_pivot_2 <- subset(data, pivot == "pivot_2")

# Crear el gráfico de dispersión para el pivote 2
ggplot(data_pivot_2, aes(x = n, y = expected_length)) +
  geom_point() +
  labs(title = "Comparación del Pivote 2 por Longitud Esperada y Tamaño de Muestra",
       x = "Tamaño de Muestra (n)",
       y = "Longitud Esperada") +
  theme_minimal()
```

```{r}
# Gráfico de Violín para la Longitud Esperada por Pivot
ggplot(data, aes(x = pivot, y = expected_length, fill = pivot)) +
  geom_violin() +
  labs(title = "Gráfico de Violín para la Longitud Esperada por Pivot",
       x = "Pivote",
       y = "Longitud Esperada",
       fill = "Pivote") +
  theme_minimal()


```


